In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import make_regression

In [3]:
## create the dataset 
x,y= make_regression(n_samples=1500,n_informative=5,n_features=10,n_targets=2)

In [4]:
x

array([[-1.87145619, -0.04274513,  0.67137062, ..., -2.54403389,
        -1.48786731, -0.5844419 ],
       [-0.6287858 ,  0.77744511,  0.95983292, ..., -1.6312494 ,
        -1.34913522,  2.04673886],
       [-0.08093177,  1.06388252,  1.82540312, ..., -0.64674099,
        -0.43032596,  0.95184673],
       ...,
       [-1.09957007,  0.65800847, -0.38727293, ...,  0.98718346,
        -0.17555884, -0.13211016],
       [ 0.94009619, -0.20634879, -0.42015831, ...,  0.43101181,
        -0.83462111,  0.98900696],
       [-0.96146803,  1.89323453, -0.07158844, ..., -0.0675801 ,
        -1.94826877, -1.06539814]])

In [5]:
y

array([[ -59.01682576, -422.97489431],
       [   4.62601861, -237.82583729],
       [ 168.2476078 ,   22.95018066],
       ...,
       [  61.77468257,   78.84172723],
       [ -79.62754185,  -19.18141962],
       [-177.56851614, -264.27331044]])

In [7]:
## now using linear regression
from sklearn.linear_model import LinearRegression

In [8]:
lrregression = LinearRegression()
lrregression.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
test_data=[[-0.32165,0.39384,-2.43284,1.23411,-1.43954,0.32665,-0.52332,0.67323,-0.11984,0.39845]]

In [13]:
lrregression.predict(test_data)

array([[-128.62563118,  -36.57783248]])

In [14]:
## now using decision tree Regressor
from sklearn.tree import DecisionTreeRegressor

In [15]:
dtregressor=DecisionTreeRegressor()
dtregressor.fit(x,y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [16]:
dtregressor.predict(test_data)

array([[ -96.14369496, -102.88403014]])

In [19]:
##using Random forest Regressor
from sklearn.ensemble import RandomForestRegressor


In [20]:
rdregressor = RandomForestRegressor()
rdregressor.fit(x,y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [21]:
rdregressor.predict(test_data)

array([[-83.32695371,   5.67067761]])

In [22]:
from sklearn.model_selection import cross_val_score

In [23]:
scores=cross_val_score(rdregressor,x,y,scoring='neg_mean_squared_error',cv=5)
print(scores)

[-1731.41880454 -1829.1716642  -1705.23267976 -1702.3035317
 -1855.18074976]


In [27]:
from sklearn.svm import LinearSVR
svregressor=LinearSVR()
svregressor.fit(x,y)
## not all support multiple dependent output 
## so to overcome this we have the below codes to use

ValueError: bad input shape (1500, 2)

In [28]:
from sklearn.multioutput import MultiOutputRegressor
mulregressor=MultiOutputRegressor(svregressor)
mulregressor.fit(x,y)
mulregressor.predict(test_data)

array([[-128.62563118,  -36.57783248]])